import typing
from pathlib import Path

from src.domain.models import Block, Book, Chapter, Progress


class BookRepository(typing.Protocol):
    """Puerto para acceso a datos del libro y progreso."""

    def save_book(self, book: Book, chapters: list[Chapter], blocks: list[Block]) -> None: ...

    def get_book(self, book_id: str) -> Book | None: ...

    def list_books(self) -> list[Book]: ...

    def get_chapters(self, book_id: str) -> list[Chapter]: ...

    def get_blocks(self, book_id: str, chapter_idx: int) -> list[Block]: ...

    def save_progress(self, progress: Progress) -> None: ...

    def get_progress(self, book_id: str) -> Progress | None: ...


class BookParser(typing.Protocol):
    """Puerto para parsear un archivo estático y extraer sus capítulos listos para texto."""

    def parse_to_chapters(self, file_path: Path, book_id: str) -> list[tuple[Chapter, str]]: ...


class TtsEngine(typing.Protocol):
    """Puerto para interactuar con motores TTS locales."""

    def start(self) -> None: ...

    def speak(self, text: str) -> None: ...

    def stop(self) -> None: ...

    def pause(self) -> None: ...

    def set_rate(self, rate: int) -> None: ...

    def set_voice(self, voice_id: str) -> None: ...

    def list_voices(self) -> list[tuple[str, str]]: ...

    def is_speaking(self) -> bool: ...


class Clock(typing.Protocol):
    """Puerto para manejar el tiempo (útil para pruebas y guardado periódico)."""

    def now(self) -> float: ...
